version: '3.8'

services:
  postgresql-primary:
    image: bitnami/postgresql:latest
    container_name: postgresql-primary
    restart: always
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=my_database
    ports:
      - "5432:5432"
    volumes:
      - postgresql_primary_data:/bitnami/postgresql
    networks:
      - postgresql_network

  postgresql-replica:
    image: bitnami/postgresql:latest
    container_name: postgresql-replica
    restart: always
    depends_on:
      - postgresql-primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_MASTER_USER=admin
      - POSTGRESQL_MASTER_PASSWORD=admin123
    ports:
      - "5433:5432"
    volumes:
      - postgresql_replica_data:/bitnami/postgresql
    networks:
      - postgresql_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    networks:
      - postgresql_network

volumes:
  postgresql_primary_data:
  postgresql_replica_data:

networks:
  postgresql_network:
    driver: bridge
